"""generate base url mapping.

Revision ID: 37c8fc365f07
Revises:
Create Date: 2025-08-22 20:03:40.453327

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37c8fc365f07"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_mapping",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("short_key", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("original_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("clicks_count", sa.Integer(), nullable=False),
        sa.Column("last_clicked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_url_mapping")),
    )
    op.create_index(op.f("ix_url_mapping_id"), "url_mapping", ["id"], unique=False)
    op.create_index(op.f("ix_url_mapping_short_key"), "url_mapping", ["short_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_mapping_short_key"), table_name="url_mapping")
    op.drop_index(op.f("ix_url_mapping_id"), table_name="url_mapping")
    op.drop_table("url_mapping")
    # ### end Alembic commands ###
