"""generate base url mapping.

Revision ID: 63ee6b6fd549
Revises:
Create Date: 2025-08-22 19:46:20.956900

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63ee6b6fd549"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlmapping",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("short_key", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("original_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("clicks_count", sa.Integer(), nullable=False),
        sa.Column("last_clicked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_urlmapping")),
    )
    op.create_index(op.f("ix_urlmapping_id"), "urlmapping", ["id"], unique=False)
    op.create_index(op.f("ix_urlmapping_short_key"), "urlmapping", ["short_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urlmapping_short_key"), table_name="urlmapping")
    op.drop_index(op.f("ix_urlmapping_id"), table_name="urlmapping")
    op.drop_table("urlmapping")
    # ### end Alembic commands ###
